# Generated by Django 6.0 on 2026-01-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact_Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200, unique=True)),
                ("msg", models.CharField(max_length=200)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
