# Generated by Django 6.0 on 2026-01-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee_app", "0002_contact_query"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact_query",
            name="email",
            field=models.EmailField(max_length=200),
        ),
    ]
